### ISSUE TITLE
Error starting the client: "grunt serve" command

### ISSUE THREAD

**Issue by bachagas** [mrooding/angular-1.3-validators#1]
Nice post, thanks!
However, for some reason, I couldn't see it running live because the "grunt serve" command is failing:
```bash
$ grunt serve
Loading "connect_proxy.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined

Running "serve" task
Warning: Task "configureProxies:server" not found. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-05-01 16:27:16 UTC)
loading tasks   7ms  ■■■■■■■■■■■■■■■ 30%
serve          13ms  ■■■■■■■■■■■■■■■■■■■■■■■■■■■ 57%
Total 23ms
```
Any idea what can be going wrong?
Note: I am on Windows 8 with git bash.
Best regards,

**Comment by mrooding** [comment]
Hi Bruno,

There was an issue related to grunt-connect-proxy which seemed to cause this problem: https://github.com/drewzboto/grunt-connect-proxy/pull/96. 

I've updated the package.json to use the latest version of grunt-connect-proxy.

If there's anything else I can help you with please let me know!

Kind regards

Marc

**Comment by bachagas** [comment]
Hello Marc!
Thanks a lot!
It did work now!
The only other small issue was the app looking for the script
"validatorWithCallback.js" which was named "validateWithCallback.js", that
I solved renaming it.
Just to let you know if you want to fix.
And thanks again for the post and for sharing.
Best regards,
Bruno

2015-05-07 7:05 GMT-03:00 Marc Rooding <notifications@github.com>:

**Comment by mrooding** [comment]
Hi Bruno,

I just fixed and pushes this too. Thanks for notifying me!

Kind regards

Marc
